### PR TITLE
Itinerary export: travelIndex numbers each stop of a tour

### LINKED ISSUE #129: travelIndex for Travelers_Itineraries tsv broken
Related to a.travelindexTotal

### PR DESCRIPTION
**Pull request by ryanctan**
Fixes #129.

### CODE REVIEW

File: query.js [hunk 1]
```diff
@@ -664,6 +664,8 @@ function parseExport(res) {
         }))
 
         // travels
+        var travelIndexCount = 0;
+
         if (d.travels && d.travels.length) d.travels.forEach(a => travels.push({
```
Comment (epicfaace) [inline query.js]: To make this code a bit more readable, I would suggest doing something like this: 

```suggestion
        if (d.travels && d.travels.length) d.travels.forEach((a, i) => travels.push({
```

This would make `i` equal to the index. Then you can set travelIndex to `i + 1`.

**Review by epicfaace — CHANGES_REQUESTED** [review]
Looks good, just a small comment.

We should also eventually document somewhere that both the travelIndex and travelindexTotal fields are no longer used and irrelevant to the data itself (since the index is only determined by the position of the travel in the array). (https://github.com/cestastanford/grandtour/blob/ae77ab4ba17d4084a4aedfaaf46b05a511808c40/models/entry-fields/travels.js#L19)

**Comment by ryanctan** [comment]
@epicfaace changes made and ready for review, index was also changed to zero-based

**Comment by epicfaace** [comment]
Thanks. I don't think "trivial" may be the right word - these fields are more "unused" and should probably eventually be deleted from the database.

**Comment by ryanctan** [comment]
@epicfaace done!

**Review by epicfaace — APPROVED** [review]
