### PR TITLE
Explore interface bugs

### LINKED ISSUE #179: bug in alpha for red negative strike through
when you click to red negative strike through in the name search box, the red does not revert to normal after consecutive clicking: it seems to be the case only in this search box, but worthwhile trying for more

Screen Shot 2019-08-26 at 5 51 03 PM

### LINKED ISSUE #180: bug alpha question marks
as you explore explore page a question marks remains floating, see pic here, where it seems to eb the one from travel date that has moved up in above search box?
Screen Shot 2019-08-26 at 5 43 46 PM

### PR DESCRIPTION
**Pull request by ryanctan**
Fixes #179, where NOT queries for traveler names would fail and fixes #180, where floating question marks would appear.

### CODE REVIEW

**Review by epicfaace — CHANGES_REQUESTED** [review]
You've changed parseQuery, which, as you can tell, has a bunch of complicated logic. That's why I made a file with test cases for it! This way, we make sure that although the logic is complicated, it does what we want and never breaks when we add more logic to it. 

Could you add some test cases that test the particular cases in which value is an array (and thus trigger the new code you added)? Here is the file: https://github.com/cestastanford/grandtour/blob/master/__tests__/query.unit.test.js

You should be able to just base your test cases off the existing ones. You can run the tests (to make sure they all pass) by doing `npm test`. Let me know if you have any questions!

**Comment by epicfaace** [comment]
@ryanctan the snapshots are stored in https://github.com/cestastanford/grandtour/blob/master/__tests__/__snapshots__/query.unit.test.js.snap. They store the expected results for each test. 

When you run a test for the first time with `toMatchSnapshot`, it generates a snapshot. You can update the snapshots by doing `npm test -- -u`. More info on snapshots here: https://jest-bot.github.io/jest/docs/snapshot-testing.html

File: query.js [hunk 1]
```diff
@@ -429,7 +429,14 @@ function parseQuery(query) {
                     let item = searchMap[k](queryItem._id, true);
                     if (queryItem.negative === true && queryItem._id !== "entry") {
                         for (let key in item) {
-                            item[key] = { $not: item[key] };
+                            let value = item[key];
+                            if (Array.isArray(value)) { // in the case that an array of queries is given, the entire array is negated with the $nor operator
```
Comment (epicfaace) [inline query.js:433]: @ryanctan perhaps you could be a bit more specific with this comment. When you say "an array of queries is given", it sounds like you're referring to the original query passed in to `parseQuery`. However, you're actually referring to `item`, which is a value in `searchMap`.

So maybe you could word it to something like "in the case an array is returned from searchMap"?
